import { useEffect, useMemo, useState } from 'react';
import { Save, Trash2 } from 'lucide-react';

type Quality = 'white'|'blue'|'purple'|'red'|'yellow';
type Prize = { id:number; quality:Quality; qualityLabel:string; title:string; rewardType:string; rewardValue:string; imageUrl:string|null; weight:number; isActive:boolean; sortOrder:number };
const qualityLabels:Record<Quality,string> = { white:'Біле · звичайне', blue:'Синє · рідкісне', purple:'Фіолетове · епічне', red:'Червоне · легендарне', yellow:'Жовте · міфічне' };
const blank=():Prize=>({id:0,quality:'white',qualityLabel:'Звичайне',title:'',rewardType:'item',rewardValue:'',imageUrl:'',weight:1,isActive:true,sortOrder:0});

export default function RouletteAdmin({actorId}:{actorId:number}){
  const [prizes,setPrizes]=useState<Prize[]>([]);const [quality,setQuality]=useState<Quality|'all'>('all');const [form,setForm]=useState<Prize>(blank);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
  async function load(){const response=await fetch(`/api/roulette?admin=1&actorId=${actorId}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'Не вдалося завантажити призи');setPrizes(data.prizes||[])}
  useEffect(()=>{load().catch(error=>setStatus(error instanceof Error?error.message:'Помилка завантаження'))},[actorId]);
  const visible=useMemo(()=>quality==='all'?prizes:prizes.filter(prize=>prize.quality===quality),[prizes,quality]);
  async function save(){setBusy(true);setStatus('');try{const response=await fetch('/api/roulette',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',actorId,...form})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Не вдалося зберегти приз');await load();setForm(blank());setStatus('Приз збережено')}catch(error){setStatus(error instanceof Error?error.message:'Помилка')}finally{setBusy(false)}}
  async function remove(id:number){if(!window.confirm('Видалити цей приз?'))return;setBusy(true);try{const response=await fetch('/api/roulette',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',actorId,id})});if(!response.ok)throw new Error('Не вдалося видалити приз');await load();if(form.id===id)setForm(blank());setStatus('Приз видалено')}catch(error){setStatus(error instanceof Error?error.message:'Помилка')}finally{setBusy(false)}}
  return <div className="roulette-admin"><div className="admin-list-heading"><h3>Призи рулетки</h3><button className="button outline" onClick={()=>setForm(blank())}>+ НОВИЙ ПРИЗ</button></div>{status&&<p className="account-admin-status">{status}</p>}<label className="roulette-admin-filter">ЯКІСТЬ<select value={quality} onChange={event=>setQuality(event.target.value as Quality|'all')}><option value="all">Усі якості</option>{Object.entries(qualityLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="roulette-admin-layout"><div className="roulette-admin-list">{visible.map(prize=><button key={prize.id} className={`roulette-admin-row quality-${prize.quality} ${form.id===prize.id?'selected':''}`} onClick={()=>setForm(prize)}><span><strong>{prize.title}</strong><small>{qualityLabels[prize.quality]} · вага {prize.weight}</small></span><span>#{prize.id}</span></button>)}</div><form className="roulette-admin-form" onSubmit={event=>{event.preventDefault();save()}}><h3>{form.id?'Редагування призу':'Новий приз'}</h3><label>ЯКІСТЬ<select value={form.quality} onChange={event=>setForm({...form,quality:event.target.value as Quality})}>{Object.entries(qualityLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>НАЗВА<input value={form.title} onChange={event=>setForm({...form,title:event.target.value})} required/></label><label>ТИП НАГОРОДИ<input value={form.rewardType} onChange={event=>setForm({...form,rewardType:event.target.value})} placeholder="skin, vehicle, money, item"/></label><label>ЗНАЧЕННЯ<input value={form.rewardValue} onChange={event=>setForm({...form,rewardValue:event.target.value})} placeholder="ID скіна або сума"/></label><label>URL ЗОБРАЖЕННЯ<input value={form.imageUrl||''} onChange={event=>setForm({...form,imageUrl:event.target.value})} placeholder="/assets/skins/130x160/257.png"/></label><div className="admin-form-grid"><label>ВАГА<input type="number" min="0" step="0.1" value={form.weight} onChange={event=>setForm({...form,weight:Number(event.target.value)})}/></label><label>ПОРЯДОК<input type="number" value={form.sortOrder} onChange={event=>setForm({...form,sortOrder:Number(event.target.value)})}/></label></div><label className="admin-check"><input type="checkbox" checked={form.isActive} onChange={event=>setForm({...form,isActive:event.target.checked})}/> Активний приз</label><div className="admin-form-actions"><button className="button gold" disabled={busy}><Save size={16}/> ЗБЕРЕГТИ</button>{form.id&&<button type="button" className="button danger" onClick={()=>remove(form.id)}><Trash2 size={16}/> ВИДАЛИТИ</button>}</div></form></div></div>;
}
