import { createContext, useContext, type ReactNode } from 'react';
import { motion } from 'framer-motion';
import { ArrowUpRight } from 'lucide-react';
import { siteConfig, type LinkKey } from '../../config/site';
export interface OverlayContent {title:string;body?:string;image?:string;galleryIndex?:number;video?:string;}
export const OverlayContext=createContext<(content:OverlayContent)=>void>(()=>{});
export function ConfigLink({configKey,children,className='',label}:{configKey:LinkKey;children:ReactNode;className?:string;label?:string}){const show=useContext(OverlayContext);const url=String(siteConfig[configKey]);return <a href={url} className={className} onClick={e=>{if(!url||url==='#'){e.preventDefault();show({title:label??'Незабаром у PRIME',body:configKey==='launcherUrl'?'Офіційне посилання на лаунчер ще не опубліковано. Завантаження стане доступним після його додавання командою PRIME RP.':'Цей розділ ще не відкрито. Офіційне посилання з’явиться після підключення сервісу командою PRIME RP.'});}}}>{children}</a>}
export function Art({name,alt='',className='',eager=false,style}:{name:string;alt?:string;className?:string;eager?:boolean;style?:React.CSSProperties}){return <img className={className} src={`/assets/${name}-1600.webp`} srcSet={`/assets/${name}-800.webp 800w, /assets/${name}-1600.webp 1600w`} sizes="(max-width: 768px) 100vw, 90vw" alt={alt} width="1600" height="900" loading={eager?'eager':'lazy'} fetchPriority={eager?'high':undefined} decoding="async" style={style}/>}
export function Reveal({children,className='',id}:{children:ReactNode;className?:string;id?:string}){return <motion.section id={id} className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.08}} transition={{duration:.7}}>{children}</motion.section>}
export function SectionTitle({eyebrow,title,accent,children}:{eyebrow:string;title:string;accent?:string;children?:ReactNode}){return <div className="section-heading"><div><p className="eyebrow"><span/>{eyebrow}</p><h2>{title} {accent&&<em>{accent}</em>}</h2></div>{children}</div>}
export function StartButton({children='ПОЧАТИ ГРАТИ',className=''}:{children?:ReactNode;className?:string}){return <a className={`button gold ${className}`} href="#start">{children}<ArrowUpRight size={19}/></a>}
export function Brand({footer=false}:{footer?:boolean}){return <a className={`brand ${footer?'brand-footer':''}`} href="#home" aria-label="PRIME RP — на головну"><img src="/assets/logo.webp" alt="PRIME RP" width="85" height="85"/><span>PRIME<span className="brand-rp">RP</span><small>UKRAINIAN ROLEPLAY</small></span></a>}
